# Generated by Django 5.0.6 on 2024-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image_subcatg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='subcatg',
            field=models.ManyToManyField(blank=True, to='eshop_app.subcategories'),
        ),
    ]
