# Generated by Django 5.0.6 on 2024-08-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0003_categories_image_subcatg_alter_categories_subcatg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='image_subcatg',
        ),
    ]
