# Generated by Django 5.0.6 on 2024-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_app', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, to='eshop_app.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
